class AuthError(Exception):
    pass

class CommandStopError(Exception):
    pass